collections:
  products:
    output: true
    permalink: /products/:path/
  campaigns:
    output: true
    permalink: /campaigns/:path/
  shop:
    output: true
    permalink: /shop/:path/
# plugins:
  # - jekyll-target-blank
