skus:

- id: junmai-shu
  category: sake
  displayName: junmai-shu
  displayHeader: Junmai-shu 720ml
  imageName: junmai-shu.png
  imageAltName: junmai shu sake bottle
  url: junmai-shu
  metaDescription: Nakano junmai-shu sake - from the Kinokuniya Bunzaemon series.
  description: |
    Nakano’s multi-award winning signature junmai-shu sake.

    Smooth, full-bodied and carefully crafted using yamada-nishiki (the ‘King’ of sake rice) and dewasanzan (rice famous for its rich aroma).

    The balance of umami and slightly tart and fruity notes makes for a superbly drinkable junmai-shu.
  medalImage: junmai-shu-medal.svg
  smoothDryImage: junmai-smooth-dry.svg
  bodyImage: junmai-body.svg
  serveWarm: true
  serveHot: false
  chilledTemp: 5° - 10°
  warmTemp: ~ 40°
  hasAwards: true
  awardName: Gold at the US National Sake Appraisal
  volume: 720ml
  alcoholContent: 15%


- id: namachozo
  category: sake
  description: |
    This junmai-shu is brewed using the same dewasanzan and yamada-nishiki rice grains as Nakano’s signature junmai-shu, which gives the sake the same delicate balance of umami, tartness and fruity notes.

    The sake is then raw-stored (this is the namachozō style, as sake is usually pasteurised first), for an extra crisp and refreshing finish.

    From Nakano’s multi-award-winning Kinokuniya Bunzaemon series.
  displayHeader: Namachozo junmai-shu 720ml
  displayName: namachozo
  hasAwards: false
  imageAltName: namachozo sake bottle
  imageName: namachozo.png
  metaDescription: Nakano namachozo junmai-shu sake, from the Kinokuniya Bunzaemon series.
  url: namachozo
  alcoholContent: 15%
  volume: 720ml
  # sake attributes
  bodyImage: namachozo-body.svg
  chilledTemp: 5° - 10°
  serveHot: false
  serveWarm: true
  smoothDryImage: namachozo-smooth-dry.svg
  warmTemp: ~ 40°


- id: 500mangoku
  category: sake
  displayName: gohyakumangoku
  displayHeader: Gohyakumangoku 720ml
  imageName: 500mangoku.png
  imageAltName: gohyaku mangoku sake bottle
  url: gohyakumangoku
  metaDescription: Nakano gohyakumangoku junmai-shu sake - from the Kinokuniya Bunzaemon series.
  description: |
    A multi-award-winning dry and lighter junmai-shu sake.

    The brewer's careful use of the distinctive gohyakumangoku rice variety (translates to “5 million stones”, common in Japan’s northwest) makes for a superbly refreshing sake, rich in aroma, and with a clean finish.

    Recommended for lovers of warm sake.
  hasAwards: true
  awardName: Gold at the Japan Kan Sake Awards
  medalImage: 500mangoku-medal.svg
  smoothDryImage: 500mangoku-smooth-dry.svg
  bodyImage: 500mangoku-body.svg
  serveWarm: true
  serveHot: true
  chilledTemp: 5° - 10°
  warmTemp: ~ 40°
  hotTemp: ~ 55°
  volume: 720ml
  alcoholContent: 15%


- id: ginjo
  category: sake
  displayName: ginjo
  displayHeader: Ginjo junmai-shu 720ml
  metaDescription: Nakano ginjo junmai-shu sake - from the Kinokuniya Bunzaemon series.
  imageName: ginjo.png
  imageAltName: ginjo sake bottle
  url: ginjo
  description: |
    A multi-award-winning extra smooth and aromatic junmai-ginjō (extra premium) edition from Nakano’s Kinokuniya Bunzaemon (KB) series.

    This ginjō retains Nakano’s signature craftsmanship, with umami and slightly tart and fruity notes carefully balanced. The enhanced polish ratio and careful blending of yamada-nishiki (the ‘King’ of sake rice) and omachi rice (famous for its complexity) amplify the sake’s smoothness and aroma.
  medalImage: ginjo-medal.svg
  smoothDryImage: ginjo-smooth-dry.svg
  bodyImage: ginjo-body.svg
  hasAwards: true
  awardName: Gold at the Japan Fine Sake Awards
  serveWarm: false
  serveHot: false
  chilledTemp: 5° - 10°
  warmTemp: None
  volume: 720ml
  alcoholContent: 16%


- id: ultra-white
  category: sake
  imageName: ultra-white.png
  imageAltName: ultra ginjo sake bottle
  url: ultra
  metaDescription: Nakano ultra gino junmai-shu sake, commissioned for the exclusive Kitcho restaurant.
  displayName: ultra
  displayHeader: Ultra junmai-ginjo 720ml
  description: |
    Originally commissioned for the exclusive Kitcho (吉兆) restaurant, which many critics consider as the icon of Japanese haute cuisine.

    Brewed with yamada-nishiki and omachi rice. Strong-bodied, full of umami, with a slight firmness.

    The sake is raw-stored at -5°C for at least 3 years to embed its ripeness, giving a long and crisp finish.

    Serve chilled.
  productImage: ultra-white.png
  smoothDryImage: ultra-smooth-dry.svg
  bodyImage: ultra-body.svg
  serveWarm: false
  serveHot: false
  chilledTemp: 5° - 10°
  hasAwards: false
  volume: 720ml
  alcoholContent: 16%


- id: umeshu
  category: umeshu
  imageName: umeshu.png
  imageAltName: Nakano umeshu plum wine bottle
  url: nakano-umeshu
  displayHeader: Nakano umeshu (plum wine) 720ml
  displayName: umeshu
  metaDescription: Nakano umeshu (plum wine), crafted from Wakayama Nanko ume.
  hasAwards: false
  volume: 720ml
  alcoholContent: 14%
  description: |
    Handcrafted using 100% Nanko ume grown in Japan’s Wakayama prefecture, a region famous for its ume (Japanese plums).

    A balance of initial sweetness and refreshing tartness. Enjoy as an aperitif served straight, on the rocks, or with a splash of soda.

    Nakano umeshu has Geographic Indication (GI) status as Wakayama Umeshu in Japan (the first liqueur, and thirteenth alcoholic beverage overall with GI status in Japan).


- id: yuzu
  category: umeshu
  imageName: yuzu.png
  imageAltName: yuzu umeshu bottle
  url: yuzu
  displayName: yuzu umeshu
  displayHeader: Yuzu umeshu 720ml
  metaDescription: Nakano yuzu umeshu.
  hasAwards: true
  awardName: Gold at the Lyon Spirits Competition
  volume: 720ml
  alcoholContent: 12%
  description: A unique blend of refreshing yuzu juice (Japanese citrus), beautifully blended with Nakano umeshu.


- id: honey
  category: umeshu
  imageName: honey.png
  imageAltName: honey umeshu bottle
  url: honey
  displayName: honey umeshu
  displayHeader: Honey umeshu 720ml
  metaDescription: Nakano honey umeshu (plum wine).
  hasAwards: false
  volume: 720ml
  alcoholContent: 12%
  description: Nakano umeshu, blended with elegant honey.


- id: beninanko
  category: umeshu
  displayName: ume liqueur
  displayHeader: Ume liqueur 720ml
  imageName: beninanko.png
  imageAltName: Nakano premium ume liqueur bottle
  url: ume-liqueur
  metaDescription: Nakano ume liqueur crafted from with crimson ripened (beninanko) ume plums.
  hasAwards: true
  awardName: Grand Prix Winner at the inaugural Osaka Tenjin Umeshu Competition (Japan’s biggest umeshu competition).
  volume: 720ml
  alcoholContent: 20%
  description: |
    An extra premium ume (plum) liqueur, handcrafted using only crimson ripened nanko ume from Wakayama (called "beninanko"), which have been hand-selected one-by-one and soaked in spirits on the same day.

    The producer uses one-and-a-half times the plums of Nakano’s signature umeshu, producing a liqueur with accentuated richness and flavour.


- id: mi-iri-160
  displayName: umeshu with whole ume 160ml
  displayHeader: Umeshu with whole ume 160ml
  category: umeshu
  imageName: umeshu_mi_iri_160ml.png
  imageAltName: umeshu cup with whole ume 160ml
  url: umeshu-whole-ume-160ml
  metaDescription: Nakano umeshu (plum wine) with whole plums, 160ml cup.
  hasAwards: false
  volume: 160ml
  alcoholContent: 14%
  description: Nakano umeshu, served with whole Nanko ume plums.


- displayName: umeshu with whole ume 720ml
  category: umeshu
  imageName: umeshu_mi_iri_720ml.png
  imageAltName: umeshu jar with whole ume 720ml
  id: mi-iri-720
  url: umeshu-whole-ume-720ml
  displayHeader: Umeshu with whole ume 720ml
  metaDescription: Nakano umeshu (plum wine) with whole plums, 720ml jar.
  hasAwards: false
  volume: 720ml
  alcoholContent: 14%
  description: Nakano umeshu, served with whole Nanko ume plums.


- displayName: kozue gin
  category: spirits
  imageName: kozue.png
  imageAltName: kozue gin bottle
  id: kozue
  url: kozue
  displayHeader: Kozue gin 700ml
  metaDescription: Kozue Japanese craft gin - with koyamaki umbrella pine and sansho pepper.
  description: |
    Handcrafted in small batches, using Japanese botanicals: koyamaki umbrella pine, lemon peel, unshu mandarin peel, and sansho pepper.

    Presents a delicate balance of floral pine, wild berry and sansho pepper notes on the nose, while the koyamaki pine provides a clean finish.
  hasAwards: true
  awardName: Gold at the Lyon Spirits Competition
  volume: 700ml
  alcoholContent: 47%


- displayName: kodachi gin
  category: spirits
  description: |
    Handcrafted in small batches using Japanese botanicals: sugi (Japanese redwood), hinoki (Japanese cypress), lemon peel, unshu mandarin peel, and sansho pepper. The sugi and hinoki evoke the spectacular forests of the nearby Kumano pilgrimage route.

    The unique combination of sugi and hinoki combined with juniper results in a deeper aroma, balanced with citrus, while the sansho pepper notes provide some sharpness.
  imageName: kodachi.png
  imageAltName: kodachi gin bottle
  id: kodachi
  url: kodachi
  displayHeader: Kodachi gin 700ml
  metaDescription: Kodachi Japanese craft gin - the forest fragrances of Kumano Kodo.
  hasAwards: false
  volume: 700ml
  alcoholContent: 47%


- id: kayuki
  category: spirits
  displayName: kayuki ume spirits
  displayHeader: Kayuki ume spirits 700ml
  metaDescription: Nakano's kayuki ume spirits
  productType: spirits
  imageName: kayuki.png
  imageAltName: kayuki ume spirits bottle

  url: kayuki
  description: |
    A distilled fine spirit that retains the distinctive aroma of ume.

    Vacuum-distilled using umeshu from Wakayama Nanko ume (plums) as the base.
  hasAwards: true
  awardName: Gold at the Lyon Spirits Competition
  volume: 700ml
  alcoholContent: 45%
