categories:

- category: Sake
  headingID: sake
  categoryName: sake
  products:

  - name: junmai-shu
    img-name: junmai-shu.png
    img-alt-name: junmai shu sake bottle
    tag-name: junmai-shu
    url: junmai-shu
    preview-text: Nakano’s multi-award winning signature junmai-shu sake. Smooth, full-bodied and...
  - name: namachozo
    img-name: namachozo.png
    img-alt-name: namachozo sake bottle
    tag-name: namachozo
    url: namachozo
    preview-text: This junmai-shu is brewed using the same dewasanzan and yamada-nishiki rice grains...


  - name: gohyakumangoku
    img-name: 500mangoku.png
    img-alt-name: gohyaku mangoku sake bottle
    tag-name: 500mangoku
    url: gohyakumangoku
    preview-text: A multi-award-winning dry and lighter junmai-shu. The brewer's careful use of the...


  - name: ginjo
    img-name: ginjo.png
    img-alt-name: ginjo sake bottle
    tag-name: ginjo
    url: ginjo
    preview-text: A multi-award-winning extra smooth and aromatic junmai-ginjō (extra premium)...


  - name: ultra
    img-name: ultra-white.png
    img-alt-name: ultra ginjo sake bottle
    tag-name: ultra-white
    url: ultra
    preview-text: Originally commissioned for the exclusive Kitcho (吉兆) restaurant, which many...

- category: Umeshu (plum wine)
  headingID: umeshu
  categoryName: umeshu
  products:

  - name: umeshu
    img-name: umeshu.png
    img-alt-name: Nakano umeshu plum wine bottle
    tag-name: umeshu
    url: nakano-umeshu
    preview-text: Handcrafted using 100% Nanko ume grown in Japan’s Wakayama prefecture, a region...

  - name: yuzu umeshu
    img-name: yuzu.png
    img-alt-name: yuzu umeshu bottle
    tag-name: yuzu
    url: yuzu
    preview-text: A unique blend of refreshing yuzu juice (Japanese citrus), beautifully blended...


  - name: honey umeshu
    img-name: honey.png
    img-alt-name: honey umeshu bottle
    tag-name: honey
    url: honey
    preview-text: Nakano umeshu, blended with elegant honey.

  - name: ume liqueur
    img-name: beninanko.png
    img-alt-name: Nakano premium ume liqueur bottle
    tag-name: beninanko
    url: ume-liqueur
    preview-text: An extra premium ume (plum) liqueur, handcrafted using only crimson ripened...

  - name: umeshu with whole ume 160ml
    img-name: umeshu_mi_iri_160ml.png
    img-alt-name: umeshu cup with whole ume 160ml
    tag-name: mi-iri-160
    url: umeshu-whole-ume-160ml
    preview-text: Nakano umeshu, served with whole Nanko ume plums.

  - name: umeshu with whole ume 720ml
    img-name: umeshu_mi_iri_720ml.png
    img-alt-name: umeshu jar with whole ume 720ml
    tag-name: mi-iri-720
    url: umeshu-whole-ume-720ml
    preview-text: Nakano umeshu, served with whole Nanko ume plums.

- category: Spirits
  headingID: spirits
  categoryName: spirits
  products:

  - name: kozue gin
    img-name: kozue.png
    img-alt-name: kozue gin bottle
    tag-name: kozue
    url: kozue
    preview-text: Handcrafted in small batches, using Japanese botanicals - koyamaki umbrella pine...

  - name: kodachi gin
    img-name: kodachi.png
    img-alt-name: kodachi gin bottle
    tag-name: kodachi
    url: kodachi
    preview-text: Handcrafted in small batches using Japanese botanicals - sugi (Japanese redwood)...

  - name: kayuki ume spirits
    img-name: kayuki.png
    img-alt-name: kayuki ume spirits bottle
    tag-name: kayuki
    url: kayuki
    preview-text: A distilled fine spirit that retains the distinctive aroma of ume...
