categories:

- category: Sake
  headingID: sake
  categoryName: sake
  products:

  - name: junmai-shu
    img-name: junmai-shu.png
    img-alt-name: junmai shu sake bottle
    tag-name: junmai-shu
    url: junmai-shu

  - name: namachozo
    img-name: namachozo.png
    img-alt-name: namachozo sake bottle
    tag-name: namachozo
    url: namachozo

  - name: gohyakumangoku
    img-name: 500mangoku.png
    img-alt-name: gohyaku mangoku sake bottle
    tag-name: 500mangoku
    url: gohyakumangoku

  - name: ginjo
    img-name: ginjo.png
    img-alt-name: ginjo sake bottle
    tag-name: ginjo
    url: ginjo

  - name: ultra
    img-name: ultra-white.png
    img-alt-name: ultra ginjo sake bottle
    tag-name: ultra-white
    url: ultra

- category: Umeshu (plum wine)
  headingID: umeshu
  categoryName: umeshu
  products:

  - name: umeshu
    img-name: umeshu.png
    img-alt-name: Nakano umeshu plum wine bottle
    tag-name: umeshu
    url: nakano-umeshu

  - name: yuzu umeshu
    img-name: yuzu.png
    img-alt-name: yuzu umeshu bottle
    tag-name: yuzu
    url: yuzu

  - name: honey umeshu
    img-name: honey.png
    img-alt-name: honey umeshu bottle
    tag-name: honey
    url: honey

  - name: ume liqueur
    img-name: beninanko.png
    img-alt-name: Nakano premium ume liqueur bottle
    tag-name: beninanko
    url: ume-liqueur

  - name: umeshu with whole ume 160ml
    img-name: umeshu_mi_iri_160ml.png
    img-alt-name: umeshu cup with whole ume 160ml
    tag-name: mi-iri-160
    url: umeshu-whole-ume-160ml

  - name: umeshu with whole ume 720ml
    img-name: umeshu_mi_iri_720ml.png
    img-alt-name: umeshu jar with whole ume 720ml
    tag-name: mi-iri-720
    url: umeshu-whole-ume-720ml

- category: Spirits
  headingID: spirits
  categoryName: spirits
  products:

  - name: kozue gin
    img-name: kozue.png
    img-alt-name: kozue gin bottle
    tag-name: kozue
    url: kozue

  - name: kodachi gin
    img-name: kodachi.png
    img-alt-name: kodachi gin bottle
    tag-name: kodachi
    url: kodachi

  - name: kayuki ume spirits
    img-name: kayuki.png
    img-alt-name: kayuki ume spirits bottle
    tag-name: kayuki
    url: kayuki
