skus:

- id: junmai-shu
  category: sake
  description: |
    Nakano’s multi-award winning signature junmai-shu sake.

    Smooth, full-bodied and carefully crafted using yamada-nishiki (the King of sake
    rice - sometimes also called the cabernet sauvignon of sake rice) and dewasanzan
    (rice famous for its rich aroma). The balance of umami, a slight tartness and fruity
    notes makes for a superbly drinkable junmai-shu.

    Pairs well with robust flavours, e.g. soy sauce based dishes, rock oysters, or a paella.

  displayName: junmai-shu
  displayHeader: Junmai-shu 720ml
  imageName: junmai-shu.png
  imageAltName: junmai shu sake bottle
  url: junmai-shu
  metaDescription: Nakano junmai-shu sake - from the Kinokuniya Bunzaemon series.
  medalImage: junmai-shu-medal.svg
  smoothDryImage: junmai-smooth-dry.svg
  bodyImage: junmai-body.svg
  serveWarm: true
  serveHot: false
  chilledTemp: 5° - 10°
  warmTemp: ~ 40°
  hasAwards: true
  awardName: Gold at the US National Sake Appraisal
  volume: 720ml
  alcoholContent: 15%
  polishRatio: 65%
  riceVarieties: yamada-nishiki, dewasanzan
  fullProductName: Nakano Kinokuniya Bunzaemon Junmai-shu
  sakeScaleValue: '+4'


- id: namachozo
  category: sake
  description: |
    This junmai-shu is brewed using the same yamada-nishiki and dewasanzan rice
    grains as Nakano’s signature junmai-shu, which gives the sake the same delicate
    balance of umami, tartness and fruity notes.

    The sake is then raw-stored (this is the namachozō style, as sake is usually
    pasteurised first). This gives the sake a longer finish and a more distinctive
    aroma.

    Just like Nakano's signature junmai-shu, this sake pairs well with robust
    flavours, e.g. soy sauce based dishes, rock oysters, or a paella.

  displayHeader: Namachozo junmai-shu 720ml
  displayName: namachozo
  hasAwards: false
  imageAltName: namachozo sake bottle
  imageName: namachozo.png
  metaDescription: |
    Nakano namachozo junmai-shu sake, from the Kinokuniya Bunzaemon series.
  url: namachozo
  alcoholContent: 15%
  volume: 720ml
  bodyImage: namachozo-body.svg
  chilledTemp: 5° - 10°
  serveHot: false
  serveWarm: true
  smoothDryImage: namachozo-smooth-dry.svg
  warmTemp: ~ 40°
  polishRatio: 65%
  riceVarieties: yamada-nishiki, dewasanzan
  fullProductName: Nakano Kinokuniya Bunzaemon Namachozo Junmai-shu
  sakeScaleValue: '+3.5'


- id: 500mangoku
  category: sake
  description: |
    A multi-award-winning dry and lighter junmai-shu sake.

    The brewer's careful use of the distinctive *gohyakumangoku* rice variety
    (translates to “5 million stones”, common in Japan’s northwest) makes for a
    superbly refreshing sake, rich in aroma, and with a clean finish.

    Pairs well with lighter, more delicate flavours, e.g. sashimi, sushi, Bluff
    oysters, or tempura.

    Recommended for lovers of warm sake.

  displayName: gohyakumangoku
  displayHeader: Gohyakumangoku 720ml
  imageName: 500mangoku.png
  imageAltName: gohyaku mangoku sake bottle
  url: gohyakumangoku
  metaDescription: |
    Nakano gohyakumangoku junmai-shu sake recommended for lovers of hot sake.
  hasAwards: true
  awardName: Gold at the Japan Kan Sake Awards
  medalImage: 500mangoku-medal.svg
  smoothDryImage: 500mangoku-smooth-dry.svg
  bodyImage: 500mangoku-body.svg
  serveWarm: true
  serveHot: true
  chilledTemp: 5° - 10°
  warmTemp: ~ 40°
  hotTemp: ~ 55°
  volume: 720ml
  alcoholContent: 15%
  polishRatio: 65%
  riceVarieties: gohyakumangoku
  fullProductName: Nakano Kinokuniya Bunzaemon Gohyakumangoku Junmai-shu
  sakeScaleValue: '+6'


- id: ginjo
  category: sake
  description: |
    A smooth, aromatic and fruity sake. Brewed using yamada-nishiki (the King of
    sake rice) and omachi rice (famous for its complexity). The word “ginjō” means
    that at least 40% of the rice has been polished off - sake in this category
    tends to be sweeter, with a fruitier aroma.

    Enjoy this sake as the main event, or paired with a soft cheese. Try using a wider
    glass where you can experience the full fruity aroma.

  displayName: ginjo
  displayHeader: Ginjō junmai-shu 720ml
  metaDescription: Nakano ginjō junmai-shu sake - from the Kinokuniya Bunzaemon series.
  imageName: ginjo.png
  imageAltName: ginjo sake bottle
  url: ginjo
  medalImage: ginjo-medal.svg
  smoothDryImage: ginjo-smooth-dry.svg
  bodyImage: ginjo-body.svg
  hasAwards: true
  awardName: Gold at the Japan Fine Sake Awards
  serveWarm: false
  serveHot: false
  chilledTemp: 5° - 10°
  warmTemp: None
  volume: 720ml
  alcoholContent: 16%
  polishRatio: 55%
  riceVarieties: yamada-nishiki, omachi
  fullProductName: Nakano Kinokuniya Bunzaemon Ginjō Junmai-shu
  sakeScaleValue: '+3'


- id: ultra-white
  category: sake
  imageName: ultra-white.png
  imageAltName: ultra white ginjo sake bottle
  url: ultra-white
  metaDescription: |
    Nakano ultra ginjo junmai-shu sake (white label), designed to be the ultimate
    meal time sake.
  displayName: ultra (white label)
  displayHeader: Ultra junmai-ginjo (white label) 720ml
  description: |
    This sake has been designed with the goal of making the ultimate sake to enjoy
    with food.

    Pairs well with lighter, more delicate flavours, e.g. sashimi, sushi, Bluff
    oysters, or tempura.

    Strong-bodied, full of umami, with a slight firmness and a crisp finish. After
    brewing, the sake has been raw-stored at -5°C for at least 3 years to embed its
    ripeness.
  productImage: ultra-white.png
  smoothDryImage: ultra-white-smooth-dry.svg
  bodyImage: ultra-white-body.svg
  serveWarm: false
  serveHot: false
  chilledTemp: 5° - 10°
  hasAwards: false
  volume: 720ml
  alcoholContent: 16%
  polishRatio: 55%
  riceVarieties: yamada-nishiki, omachi
  fullProductName: Nakano Chokyu (Ultra) Ginjō Junmai-shu (white label)
  sakeScaleValue: '-4'


- id: ultra-red
  category: sake
  imageName: ultra-red.png
  imageAltName: ultra red ginjo sake bottle
  url: ultra-red
  metaDescription: |
    Nakano ultra ginjo junmai-shu sake (red label), brewed 100% with the rich yet
    complex bizen-omachi rice, also known as "the phantom sake rice" for its
    scarceness and difficulty to grow.
  displayName: ultra (red label)
  displayHeader: Ultra junmai-ginjo (red label) 720ml
  description: |
    Brewed 100% with the rich yet complex bizen-omachi rice, also known as "the
    phantom sake rice" for its scarceness and difficulty to grow.

    It has a smoother, juicy flavour profile (the Bordeaux red of the sake world),
    full of umami, and balanced with a tartness and crisp finish that still makes it moreish.

    This sake is best enjoyed from a wine glass where you can enjoy its full aroma.
  productImage: ultra-red.png
  smoothDryImage: ultra-red-smooth-dry.svg
  bodyImage: ultra-red-body.svg
  serveWarm: false
  serveHot: false
  chilledTemp: 5° - 10°
  hasAwards: true
  awardName: Platinum award winner at the Kura Master Competition in France.
  volume: 720ml
  alcoholContent: 16%
  polishRatio: 55%
  riceVarieties: bizen-omachi
  fullProductName: Nakano Chokyu (Ultra) Ginjō Junmai-shu (red label)
  sakeScaleValue: '-4.5'

- id: ultra-super-dry
  category: sake
  imageName: ultra-super-dry.png
  imageAltName: ultra super dry junmai-shu sake bottle
  url: ultra-super-dry
  metaDescription: Nakano ultra super dry junmai-shu sake.
  displayName: ultra (super dry)
  displayHeader: Ultra super dry 720ml
  description: |
    Brewed to extract the very maximum umami from rice, this junmai-shu from
    Nakano's ultra series measures +17.8 on the sake scale. While this places it
    at the super-dry end of the sake spectrum at face value, it carries an umami
    that blooms in the mouth, giving the sake a gentler flavour profile.

    This is a junmai-shu that allows the drinker to enjoy both the true umami of
    rice, alongside a very clean finish.

    Pairs well with lighter, more delicate flavours, e.g. sashimi, sushi, Bluff
    oysters, tempura, or panko crumbed fish or chicken. Or enjoy as a palate
    cleanser with fried foods like fish and chips.
  productImage: ultra-super-dry.png
  smoothDryImage: ultra-super-dry-smooth-dry.svg
  bodyImage: ultra-super-dry-body.svg
  serveWarm: false
  serveHot: true
  chilledTemp: 5° - 10°
  hotTemp: 50°
  hasAwards: false
  volume: 720ml
  alcoholContent: 19%
  polishRatio: 65%
  fullProductName: Nakano Chokyu (Ultra) Junmai-shu (super dry)
  sakeScaleValue: '+18'

- id: ultra-green
  category: sake
  imageName: ultra-green.png
  imageAltName: ultra green ginjo sake bottle
  url: ultra-green
  metaDescription: |
    Nakano ultra ginjo junmai-shu sake (green label), brewed using 100% yamada-
    nishiki rice from the Kita-ikiki collective in the Kyushu highlands.
  displayName: ultra (green label)
  displayHeader: Ultra junmai-ginjo (green label) 720ml
  description: |
    Brewed using 100% yamada-nishiki rice (aka the King of sake rice - sometimes
    also called the cabernet sauvignon of sake rice) from the Kita-iki-iki Collective
    in Minami-aso village in the Kyushu highlands, who are famous for their pure waters
    and sustainable farming methods.

    The rice is polished down to 55% to produce a very clear sake, with elegant
    aroma and subtle umami.

    The sake rice has been grown using “natural cultivation”. This is a farming
    method that does not use any pesticides, herbicides or fertilisers (including
    organic fertilisers). It relies solely on the power of nature to grow crops.
    The yield is lower than more traditional rice farming and weeding is more
    difficult. There is no compromise on the quality of the sake rice, while the
    beautiful Minami-aso environment is safeguarded for future generations.

    Pair this sake with snacks or dishes with a good umami profile, e.g. mushroom
    risotto, avocado, parmesan or gouda cheese, or tomato based pasta dishes.
  productImage:  ultra-green.png
  smoothDryImage: ultra-green-smooth-dry.svg
  bodyImage: ultra-green-body.svg
  serveWarm: false
  serveHot: false
  chilledTemp: 5° - 10°
  hasAwards: false
  volume: 720ml
  alcoholContent: 16%
  fullProductName: Nakano Chokyu (Ultra) Ginjo Junmai-shu (green label)
  riceVarieties: Minami-Aso yamada-nishiki
  sakeScaleValue: '+4.5'
  polishRatio: 55%

- id: josen
  category: sake
  description: |
    A smooth sake that can be enjoyed chilled or heated, with an umami that
    blooms in the mouth.

    When heated to 50°C, the sake retains its smoothness and clean finish, without any
    bitterness developing, and you can enjoy more of the rich rice aroma.

    Pairs well with seafood and chicken dishes.

  imageName: josen.png
  imageAltName: josen sake 180ml cup
  url: josen
  metaDescription: Josen (Blue Dragon) cup sake from Nakano.
  displayName: Blue Dragon (josen) cup 180ml
  displayHeader: Blue Dragon (josen) sake cup 180ml
  productImage:  josen.png
  smoothDryImage: josen-smooth-dry.svg
  bodyImage: josen-body.svg
  serveHot: true
  chilledTemp: 5° - 10°
  hotTemp: 50°
  hasAwards: false
  volume: 180ml
  alcoholContent: 15%
  fullProductName: Nakano Chokyu (Blue Dragon / josen) cup sake
  sakeScaleValue: '+3.5'



- id: umeshu
  category: umeshu
  imageName: umeshu.png
  imageAltName: Nakano umeshu plum wine bottle
  url: nakano-umeshu
  displayHeader: Nakano umeshu (plum wine) 720ml
  displayName: umeshu
  metaDescription: Nakano umeshu (plum wine), crafted from Wakayama Nanko ume.
  hasAwards: false
  volume: 720ml
  alcoholContent: 14%
  description: |
    Crafted using 100% Nanko ume grown in Japan’s Wakayama prefecture, which
    have been hand-sorted and soaked in alcohol on the same day they’ve been
    harvested.

    A balance of initial sweetness and refreshing tartness. Enjoy as an aperitif
    served straight, on the rocks, or with a splash of soda.

    Nanko ume are widely regarded as the premier ume for making umeshu, due to
    their abundant flesh, soft peach-like aroma and high organic acid content.
    Wakayama Prefecture is the most famous region in Japan for ume production (in
    particular for nanko ume) due to its favourable climate.


- id: yuzu
  category: umeshu
  imageName: yuzu.png
  imageAltName: yuzu umeshu bottle
  url: yuzu
  displayName: yuzu umeshu
  displayHeader: Yuzu umeshu 720ml
  metaDescription: Nakano yuzu umeshu.
  hasAwards: true
  awardName: Gold at the Lyon Spirits Competition
  volume: 720ml
  alcoholContent: 12%
  description: |
    A refreshing blend of real yuzu juice (Japanese citrus) and Nakano's umeshu
    (plum wine). A balance of the aroma and sweetness of umeshu, with the acidity
    and citrus notes of yuzu.


- id: honey
  category: umeshu
  imageName: honey.png
  imageAltName: honey umeshu bottle
  url: honey
  displayName: honey umeshu
  displayHeader: Honey umeshu 720ml
  metaDescription: Nakano honey umeshu (plum wine).
  hasAwards: false
  volume: 720ml
  alcoholContent: 12%
  description: Nakano umeshu, blended with elegant honey.


- id: beninanko
  category: umeshu
  displayName: ume liqueur
  displayHeader: Ume liqueur 720ml
  imageName: beninanko.png
  imageAltName: Nakano premium ume liqueur bottle
  url: ume-liqueur
  metaDescription: Nakano ume liqueur crafted from with crimson ripened (beninanko) ume plums.
  hasAwards: true
  awardName: |
    Grand Prix Winner at the inaugural Osaka Tenjin Umeshu Competition (Japan’s
    biggest umeshu competition).
  volume: 720ml
  alcoholContent: 20%
  description: |
    An umeshu (plum wine) made with 100% crimson coloured nanko ume (plums) from
    Wakayama Prefecture, which have been soaked in spirits on the same day they
    are harvested. The producer also uses 150% the ume (plums) of Nakano’s signature
    umeshu.

    The result is even more richness from the ume and a gentle peach-like fragrance.

- id: mi-iri-160
  displayName: umeshu with whole ume 160ml
  displayHeader: Umeshu with whole ume 160ml
  category: umeshu
  imageName: umeshu_mi_iri_160ml.png
  imageAltName: umeshu cup with whole ume 160ml
  url: umeshu-whole-ume-160ml
  metaDescription: Nakano umeshu (plum wine) with whole plums, 160ml cup.
  hasAwards: false
  volume: 160ml
  alcoholContent: 14%
  description: |
    Nakano umeshu, served with whole Nanko ume plums.

    Nanko ume are widely regarded as the premier ume for making umeshu, due to
    their abundant flesh, soft peach-like aroma and high organic acid content.
    Wakayama Prefecture is the most famous region in Japan for ume production (in
    particular for nanko ume) due to its favourable climate.



- displayName: umeshu with whole ume 720ml
  category: umeshu
  imageName: umeshu_mi_iri_720ml.png
  imageAltName: umeshu jar with whole ume 720ml
  id: mi-iri-720
  url: umeshu-whole-ume-720ml
  displayHeader: Umeshu with whole ume 720ml
  metaDescription: Nakano umeshu (plum wine) with whole plums, 720ml jar.
  hasAwards: false
  volume: 720ml
  alcoholContent: 14%
  description: |
    Nakano umeshu, served with whole Nanko ume plums.

    Nanko ume are widely regarded as the premier ume for making umeshu, due to
    their abundant flesh, soft peach-like aroma and high organic acid content.
    Wakayama Prefecture is the most famous region in Japan for ume production (in
    particular for nanko ume) due to its favourable climate.


- id: green-tea
  displayName: green tea umeshu
  displayHeader: Green tea umeshu 720ml
  category: umeshu
  imageName: green-tea.png
  imageAltName: green tea infused umeshu bottle
  url: green-tea
  metaDescription: Nakano umeshu, infused with green tea (ryoku-cha).
  hasAwards: false
  volume: 720ml
  alcoholContent: 12%
  description: |
    Nakano umeshu, infused with green tea (ryoku-cha).

    A refreshing balance from the astringency of green tea, paired with the
    aroma and tartness of Nakano’s umeshu.


- id: shiso
  displayName: red shiso umeshu
  displayHeader: Red shiso umeshu 720ml
  category: umeshu
  imageName: shiso.png
  imageAltName: shiso umeshu bottle
  url: shiso
  metaDescription: Nakano umeshu, infused with red shiso (perilla, also known as Japanese mint).
  hasAwards: false
  volume: 720ml
  alcoholContent: 12%
  description: |
    Nakano umeshu, infused with red shiso (perilla, also known as Japanese mint).

    A refreshing blend of the acidity and aroma of the red shiso alongside the
    sweetness and tartness of Nakano umeshu.


- displayName: kozue gin
  category: spirits
  imageName: kozue.png
  imageAltName: kozue gin bottle
  id: kozue
  url: kozue
  displayHeader: Kozue gin 700ml
  metaDescription: Kozue Japanese craft gin - with koyamaki umbrella pine and sansho pepper.
  description: |
    Handcrafted in small batches, using Japanese botanicals: koyamaki umbrella
    pine, lemon peel, unshu mandarin peel, and sansho pepper.

    Presents a delicate balance of floral pine, wild berry and sansho pepper
    notes on the nose, while the koyamaki pine provides a clean finish.
  hasAwards: true
  awardName: Gold at the Lyon Spirits Competition
  volume: 700ml
  alcoholContent: 47%


- displayName: kodachi gin
  category: spirits
  description: |
    Handcrafted in small batches using Japanese botanicals: sugi (Japanese
    redwood), hinoki (Japanese cypress), lemon peel, unshu mandarin peel, and
    sansho pepper. The sugi and hinoki evoke the spectacular forests of the
    nearby Kumano pilgrimage route.

    The unique combination of sugi and hinoki combined with juniper results in a
    deeper aroma, balanced with citrus, while the sansho pepper notes provide
    some sharpness.
  imageName: kodachi.png
  imageAltName: kodachi gin bottle
  id: kodachi
  url: kodachi
  displayHeader: Kodachi gin 700ml
  metaDescription: Kodachi Japanese craft gin - the forest fragrances of Kumano Kodo.
  hasAwards: false
  volume: 700ml
  alcoholContent: 47%


- id: kayuki
  category: spirits
  displayName: kayuki ume spirits
  displayHeader: Kayuki ume spirits 700ml
  metaDescription: Nakano's kayuki ume spirits
  productType: spirits
  imageName: kayuki.png
  imageAltName: kayuki ume spirits bottle

  url: kayuki
  description: |
    A distilled fine spirit that retains the distinctive aroma of ume.

    Vacuum-distilled using umeshu from Wakayama Nanko ume (plums) as the base.
  hasAwards: true
  awardName: Gold at the Lyon Spirits Competition
  volume: 700ml
  alcoholContent: 45%
